#!/bin/bash
#
source _env
#
if [ $sys = "darwin" ]; then
  brew install zsh
else
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  sudo apt install ./google-chrome-stable_current_amd64.deb
fi
