#!/bin/bash
#
source _env
#
if [ $sys = "linux" ]; then
sudo apt install ranger -y
sudo apt install feh atool mediainfo exiftool highlight -y
else
brew install ranger 
brew install feh atool mediainfo exiftool highlight 
fi
#
