#!/bin/bash
#
sudo apt install tmux -y

[ ! -d ~/.tmux-themepack ] && git clone https://github.com/jimeh/tmux-themepack.git ~/.tmux-themepack

[ ! -d ~/.tmux/plugins/tpm ] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
#


