#!/bin/bash
#
source _env
#
if [ $sys = "darwin" ]; then
   brew_install_or_upgrade tmux
else
   sudo apt install tmux -y
fi

if [ ! -d ~/.tmux-themepack ]; then
  git clone https://github.com/jimeh/tmux-themepack.git ~/.tmux-themepack
else
   (cd ~/.tmux-themepack; git pull)
fi

if [ ! -d ~/.tmux/plugins/tpm ]; then
   git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
   (cd ~/.tmux/plugins/tpm; git pull)
fi
#


